kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: 335903781996.dkr.ecr.us-east-2.amazonaws.com/brahim-spark-master
          resources:
            requests:
              cpu: 100m
